apiVersion: cirrus.ibm.com/v1alpha1
kind: Application
metadata:
  name: ascent-bff-test
spec:
  headless: false
  livenessProbe:
    httpGet:
      path: /health
      scheme: HTTP
    periodSeconds: 30
    timeoutSeconds: 30
  readinessProbe:
    httpGet:
      path: /health
      scheme: HTTP
    periodSeconds: 30
    timeoutSeconds: 30
  replicas: 1
  quota: q256mb
  envFrom:
    - secretRef:
        name: ascent-bff-prod
