apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: dashclinic-server
  namespace: test-dashclinic-mcm
  labels:
    name: dashclinic-server
    app: dashclinic-server
spec:
  componentKinds:
    - group: app.ibm.com
      kind: Subscription
    - group: core
      kind: Pods
    - group: apps
      kind: Deployment
    - group: route.openshift.io
      kind: Route
    - group: core
      kind: Service
  descriptor: {}
  selector:
    matchLabels:
      app: dashclinic-server
---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: dashclinic-server
  namespace: test-dashclinic-mcm
  generation: 1
  labels:
    app: dashclinic-server
spec:
  name: dashclinic-server
  channel: test-dashclinic-mcm/helm-repo-artifactory
  packageFilter:
    version: 1.1.2
  placement:
    placementRef:
      name: dashclinic-server-rule
      kind: PlacementRule
---
apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: dashclinic-server-rule
  namespace: test-dashclinic-mcm
  generation: 1
  labels:
    name: dashclinic-server-rule
    app: test-dashclinic-mcm
spec:
  clusterLabels:
    matchLabels:
      name: gsi-dev-ocp43
  clusterReplicas: 3
